
module.exports = {
     citiesArray :[
        "Montreal",
        "Shijiazhuang",
        "Rome",
        "Yaounde",
        "Tel Aviv",
        "Ningbo",
        "Kabul",
        "Xinbei",
        "Shantou",
        "Hefei",
        "Changchun",
        "Kunming",
        "Urumqi",
        "Jiddah",
        "Cape Town",
        "Brasilia",
        "Changsha",
        "Monterrey",
        "Sydney",
        "Hanoi",
        "Nairobi",
        "Melbourne",
        "Addis Ababa",
        "Chittagong",
        "Ankara",
        "Guadalajara",
        "Alexandria",
        "Fukuoka",
        "Yangon",
        "Abidjan",
        "Saint Petersburg",
        "Barcelona",
        "Ji-nan Shandong",
        "Zhengzhou",
        "Qingdao",
        "Dalian",
        "Singapore",
        "Johannesburg",
        "Khartoum",
        "Belo Horizonte",
        "Toronto",
        "Haerbin",
        "Madrid",
        "Santiago",
        "Pune",
        "Dar es Salaam",
        "Foshan",
        "Dongguan",
        "Baghdad",
        "Shenyang",
        "Riyadh",
        "Hong Kong",
        "Suzhou",
        "Surat",
        "Hangzhou",
        "Kuala Lumpur",
        "Ahmedabad",
        "Xi-an Shaanxi",
        "Wuhan",
        "New York City",
        "Luanda",
        "Ho Chi Minh City",
        "Tehran",
        "Nanjing",
        "Chengdu",
        "London",
        "Nagoya",
        "Seoul",
        "Hyderabad",
        "Bangkok",
        "Lima",
        "Jakarta",
        "Paris",
        "Bogota",
        "Chennai",
        "Moscow",
        "Shenzhen",
        "Bangalore",
        "Lahore",
        "Rio de Janeiro",
        "Guangzhou",
        "Tianjin",
        "Manila",
        "Kolkata",
        "Buenos Aires",
        "Lagos",
        "Kinshasa",
        "Istanbul",
        "Karachi",
        "Chongqing",
        "Osaka",
        "Mumbai",
        "Beijing",
        "Cairo",
        "Mexico City",
        "Sao Paulo",
        "Dhaka",
        "Shanghai",
        "Delhi",
        "Tokyo"
    ]
}
